# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J0P6FAvyhhffYDIbRAYFAtmFHMteCxgB
"""

# Object of the program: The program aims to produce buy and sell signal by using Simple Moving average crossover
# strategy where when the short term MA crosses the long term MA from below, it gives buy signal
# and when the short term MA crosses longterm MA from above, it gives sell signal

# Importing necessary packages
from datetime import datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')

#Importing the dataset
from pandas_datareader import data

#Specifying start date and end date
#I started form January 1st of 2020, to include the market crash due to covid
start_date='2018-1-1'
end_date='2020-12-1'

#Importing AAPL stock
AAPL_data=data.DataReader("AAPL","yahoo",start_date,end_date)

#Importing JPM stock
JPM_data=data.DataReader("JPM","yahoo",start_date,end_date)

#Showing the AAPL dataset
AAPL_data

#Showing the JPM dataset
JPM_data

#Plot the data
plt.figure(figsize=(13,7.5))
plt.plot(AAPL_data["Adj Close"],label="AAPL",color="blue")
plt.plot(JPM_data["Adj Close"],label="JPM",color="red")
plt.title("AAPL vs JMP")
plt.legend(loc="upper left")
plt.xlabel("Date")
plt.ylabel("$ Price")

##Analyzing the graph
#From the graph; we can see that APPL stock plummeted after Feb 20th till about 
# about the mid  of March,  then it got into upward trend untill the beginning of the september

#From the graph; we can see that JPM stock severly dropped on Feb 2nd  till about 
# about the end of March.

#Constructing the simple moving average with 20 day period for AAPL
AAPL_SMA20=pd.DataFrame()
AAPL_SMA20["Adj Close"]=AAPL_data["Adj Close"].rolling(window=20).mean()

AAPL_SMA20

#Constructing the simple moving average with 20 day period for JPM
JPM_SMA20=pd.DataFrame()
JPM_SMA20["Adj Close"]=JPM_data["Adj Close"].rolling(window=20).mean()
#JPM_SMA20

#Constructing the simple moving average with 100 day period for AAPL
AAPL_SMA100=pd.DataFrame()
AAPL_SMA100["Adj Close"]=AAPL_data["Adj Close"].rolling(window=100).mean()
AAPL_SMA100

#Constructing the simple moving average with 100 day period for JPM
JPM_SMA100=pd.DataFrame()
JPM_SMA100["Adj Close"]=JPM_data["Adj Close"].rolling(window=100).mean()
JPM_SMA100

#Plot the AAPL stock and moving averages
plt.figure(figsize=(16,10))
plt.plot(AAPL_SMA20,label="SMA20",color="yellow")
plt.plot(AAPL_SMA100,label="SMA100",color="green")
plt.plot(AAPL_data["Adj Close"],label="AAPL",color="blue")
plt.ylabel("$ Price")
plt.xlabel("Date")
plt.legend()

#Plot the JPM stock and moving averages
plt.figure(figsize=(16,10))
plt.plot(JPM_SMA20,label="SMA20",color="yellow")
plt.plot(JPM_SMA100,label="SMA100",color="green")
plt.plot(JPM_data["Adj Close"],label="JPM",color="purple")
plt.legend()
plt.ylabel("$ Price")
plt.xlabel("Date")

#Constructing a new AAPL data frame which includes Adj Close, SMA20, SMA100
AAPL_df=pd.DataFrame()
AAPL_df["SMA20"]=AAPL_SMA20["Adj Close"]
AAPL_df["SMA100"]=AAPL_SMA100["Adj Close"]
AAPL_df["AAPL"]=AAPL_data["Adj Close"]
AAPL_df

#Constructing a new JPM data frame which includes Adj Close, SMA20, SMA100
JPM_df=pd.DataFrame()
JPM_df["SMA20"]=JPM_SMA20["Adj Close"]
JPM_df["SMA100"]=JPM_SMA100["Adj Close"]
JPM_df["JPM"]=JPM_data["Adj Close"]

JPM_df

##Creating a function to give a singal of where to buy and where to sell
def signal(array):

  sig=-1
  count=0
  lis=list()

  for i in range(len(array)):

    if array["SMA20"][count]>array["SMA100"][count] and sig is not 1 :

      lis.append("buy")

      sig=1


    elif array["SMA20"][count]<array["SMA100"][count] and sig is not 0:


      lis.append("sell")
      
      sig=0



    else:
      lis.append(np.nan)

  
    count=count+1

  return lis




# signal(new_df)

#Adding the Signal and Return to the AAPL_data frame
AAPL_df["Signal_AAPL"]=signal(AAPL_df)
AAPL_df["Signal_AAPL"]
AAPL_df["AAPL_Return"]=AAPL_df[["AAPL"]].pct_change()
AAPL_df

# Adding signal and Return in dataframe
JPM_df["Signal_JPM"]=signal(JPM_df)
#JPM_df["Signal_JPM"]
JPM_df["JPM_Return"]=JPM_df[["JPM"]].pct_change()
JPM_df

# Changing the order od JPM_df

JPM_df = JPM_df[['Signal_JPM', "JPM", 'SMA20', 'SMA100']]


JPM_df = JPM_df.rename(columns={'SMA20': 'SMA20_JPM',"SMA100":"SMA100_JPM"})

JPM_df

joined_df=AAPL_df.join(JPM_df)
#JPM_df[["Signal","JPM"]])

joined_df